# Generated by Django 2.2 on 2021-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='主机名称')),
                ('ip_addr', models.CharField(max_length=32, verbose_name='主机地址')),
            ],
        ),
    ]
